### ISSUE TITLE
How to pass arguments to task

### ISSUE THREAD

**Issue by pablorcum** [matlab-actions/run-build#26]
How can I pass arguments to a task? This doesn't seem to be covered in the actions' help. Can we use directly the following actions' call?

```
- name: Run build
  uses: matlab-actions/run-build@v2
  with:
    tasks: mytask("arg1","arg2")
```
